# Generated by Django 6.0.6 on 2026-06-30 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='تاريخ الزيارة')),
                ('status', models.CharField(choices=[('planned', 'مجدولة'), ('done', 'منجزة'), ('cancelled', 'ملغاة')], default='planned', max_length=20, verbose_name='الحالة')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='الغرض من الزيارة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('result', models.TextField(blank=True, verbose_name='نتيجة الزيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clients.client', verbose_name='العميل')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='المندوب')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-visit_date'],
            },
        ),
    ]
