# Generated by Django 6.0.6 on 2026-07-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_activity_alter_client_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('actual', 'عميل فعلي'), ('potential', 'عميل محتمل')], default='potential', max_length=20, verbose_name='نوع العميل'),
        ),
    ]
