# Generated by Django 6.0.6 on 2026-07-03 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_assigned_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'المناديب'), ('accountant', 'المحاسبين'), ('review', 'المراجعة')], max_length=20, verbose_name='القسم')),
                ('commission_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent', 'نسبة مئوية')], max_length=10, verbose_name='النوع')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأعلى')),
                ('reference_note', models.TextField(blank=True, verbose_name='المبلغ المرجعي / آلية الاحتساب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قاعدة عمولة',
                'verbose_name_plural': 'قواعد العمولات',
                'unique_together': {('client', 'department')},
            },
        ),
    ]
