# Generated by Django 6.0.6 on 2026-07-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientcommissionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_commissionable',
            field=models.BooleanField(default=False, verbose_name='خاضع للعمولة'),
        ),
    ]
