# Generated by Django 6.0.6 on 2026-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_is_commissionable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل'),
        ),
        migrations.AddField(
            model_name='client',
            name='converted_status',
            field=models.CharField(blank=True, choices=[('', 'لم يُحوَّل'), ('actual', 'تم التحويل لعميل فعلي'), ('review', 'تم التحويل لقسم المراجعة')], default='', max_length=10, verbose_name='حالة التحويل'),
        ),
    ]
