# Generated by Django 6.0.6 on 2026-07-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='callmebot_api_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='CallMeBot API Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='مثال: 966501234567 (بدون + أو 00)', max_length=20, verbose_name='رقم الواتساب'),
        ),
    ]
