# Generated by Django 6.0.6 on 2026-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_callmebot_api_key_user_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'أدمن'), ('sales', 'مندوب'), ('accountant', 'محاسب'), ('review', 'مراجعة')], default='sales', max_length=20),
        ),
    ]
