# Generated by Django 6.0.6 on 2026-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='المسؤول'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_users',
            field=models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للمستخدمين'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية الاشتراك'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي'), ('custom', 'مخصص')], default='monthly', max_length=20, verbose_name='نوع الاشتراك'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start',
            field=models.DateField(blank=True, null=True, verbose_name='بداية الاشتراك'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='سوبر أدمن'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الشركة'),
        ),
    ]
