# Generated by Django 6.0.6 on 2026-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_address_tenant_contact_person_tenant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='callmebot_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='اتركه فارغاً لاستخدام بريدك الرئيسي', max_length=254, verbose_name='إيميل التنبيهات'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='احصل عليه من بوت @userinfobot', max_length=50, verbose_name='Telegram Chat ID'),
        ),
    ]
