# Generated by Django 6.0.6 on 2026-06-30 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('event_type', models.CharField(choices=[('meeting', 'اجتماع'), ('visit', 'زيارة'), ('followup', 'متابعة'), ('reminder', 'تذكير'), ('other', 'أخرى')], default='reminder', max_length=20, verbose_name='النوع')),
                ('source', models.CharField(blank=True, choices=[('review', 'قسم المراجعة'), ('sales', 'قسم المناديب'), ('accounts', 'قسم الحسابات')], max_length=20, verbose_name='القسم')),
                ('start_datetime', models.DateTimeField(verbose_name='وقت البداية')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_done', models.BooleanField(default=False, verbose_name='منجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clients.client', verbose_name='العميل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'حدث',
                'verbose_name_plural': 'الأحداث',
                'ordering': ['start_datetime'],
            },
        ),
    ]
