# Generated by Django 6.0.6 on 2026-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'قادم'), ('done', 'منجز'), ('cancelled', 'ملغي'), ('rescheduled', 'معاد جدولته')], default='pending', max_length=15, verbose_name='الحالة'),
        ),
    ]
