# Generated by Django 6.0.6 on 2026-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclient',
            name='activity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewclient',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewclient',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewclient',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reviewclient',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewclient',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
