# Generated by Django 6.0.6 on 2026-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_reviewclient_assigned_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclient',
            name='is_commissionable',
            field=models.BooleanField(default=False, verbose_name='خاضع للعمولة'),
        ),
    ]
