# Generated by Django 6.0.6 on 2026-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ السطر'),
        ),
    ]
