# Generated by Django 6.0.6 on 2026-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commissionentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsheet',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية الفترة'),
        ),
        migrations.AlterField(
            model_name='commissionsheet',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='بداية الفترة'),
        ),
    ]
