# Generated by Django 6.0.6 on 2026-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commissionsheet_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='accountant_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='عمولة المحاسب'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='accountant_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة عمولة المحاسب %'),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='عمولة المندوب'),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة عمولة المندوب %'),
        ),
    ]
