# Generated by Django 6.0.6 on 2026-07-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissionentry_accountant_commission_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionentry',
            name='accountant_commission_rate',
        ),
        migrations.RemoveField(
            model_name='commissionentry',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='review_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='عمولة المراجع'),
        ),
    ]
