# Generated by Django 6.0.6 on 2026-07-03 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_remove_commissionentry_accountant_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('commission_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent', 'نسبة مئوية')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_commission_rules', to='commissions.commissionentry')),
            ],
            options={
                'unique_together': {('entry', 'department')},
            },
        ),
    ]
