# Generated by Django 6.0.6 on 2026-07-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_is_commissionable'),
        ('commissions', '0006_entrycommissionrule'),
        ('workflow', '0004_reviewclient_is_commissionable'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='review_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.reviewclient', verbose_name='عميل المراجعة'),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='العميل'),
        ),
    ]
