# Generated by Django 6.0.6 on 2026-07-14 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_commissionentry_review_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='accountant_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_commission_entries', to=settings.AUTH_USER_MODEL, verbose_name='المحاسب'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='reviewer_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_commission_entries', to=settings.AUTH_USER_MODEL, verbose_name='المراجع'),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to=settings.AUTH_USER_MODEL, verbose_name='المندوب'),
        ),
    ]
